### PR TITLE
data:Ellah120

### PR DESCRIPTION
**Pull request by Ellah120**

### CODE REVIEW

**Comment by Ellah120** [comment]
@eddiejaoude

**Comment by eddiejaoude** [comment]
@Ellah120 you need to make the pull request to the original repo not your fork, here is the documentation https://linkfree.eddiehub.io/docs/quickstart

Any questions let us

**Comment by Ellah120** [comment]
> @Ellah120 you need to make the pull request to the original repo not your fork, here is the documentation https://linkfree.eddiehub.io/docs/quickstart
> 
> Any questions let us

yes please @eddiejaoude how do I make the request direct to the main repo please....cause reading the documentation I can't find what I did wrongly. Please can you point me in the right direction?

**Comment by eddiejaoude** [comment]
Oh the quickstart guide go to section 13 `Click compare across forks and you will see 4 drop downs` and you will see the screenshots and steps to follow

**Comment by eddiejaoude** [comment]
Btw Ellah, you can still use the same branch you have your changes in `Ellah120-patch-1` and create a new PR in the original repo http://github.com/EddieHubCommunity/LinkFree described in section `13` in the documentation

But any questions ask in us EddieHub Discord http://discord.eddiehub.org

**Pull request closed without merging**
